### ISSUE TITLE
Add directory control to smartqc

### ISSUE THREAD

**Issue by LMT337** [mgi-qc/production_pipeline_tracker#4]
Control directory structure from smartqc to enable easier updates, addition and deletion of directories.

**Comment by antonaccitj** [comment]
First iteration of this has been added in Pull #18
This could still use some polishing

**Comment by antonaccitj** [comment]
Fixes have been added with Pull #21

**Comment by antonaccitj** [comment]
No other issues with this have been reported. Closing
