### ISSUE TITLE
Add user input to qPCR dropoff instead of files

### ISSUE THREAD

**Issue by LMT337** [mgi-qc/production_pipeline_tracker#9]
Let user copy/paste inputs directly instead of creating input files.

**Comment by antonaccitj** [comment]
This one will be tricky given the script expects the -f flag. I am thinking of having it prompt when the flag is missing instead of exiting out. This will be something to add to a sprint

**Comment by antonaccitj** [comment]
This has been resolved with commit #23  and merged with master
